services:
  hefs-hub:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-install:20260818
    container_name: working-ngen-install
    ports:
      - "8888:8888"  # JupyterLab
    env_file:
      - .env  # Load AWS credentials from .env file (create from .env.example)
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser 
      --NotebookApp.token='' --NotebookApp.password=''
      --allow-root
    networks:
      - hefs-network
    restart: unless-stopped
    volumes:
      - ./.test_user_home:/home/jovyan
      - ./test_opt_ngen:/opt/ngen
volumes:
  .user_home:
  
networks:
  hefs-network:
    driver: bridge
